name: Android DEMO Build

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: sdkmanager --install "ndk;25.2.9519653"

      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install extension-androidtools > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Install patched hxcpp
        run: |
          curl --output ../hxcpp.zip --location https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.45/hxcpp-4.3.45.zip
          haxelib install ../hxcpp.zip --quiet

      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      - name: Configure Lime Android paths
        run: |
          mkdir -p ~/.lime
          cat > ~/.lime/config.xml << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <config>
              <section id="defines">
                  <define name="ANDROID_SDK" value="$ANDROID_HOME" />
                  <define name="ANDROID_NDK_ROOT" value="$ANDROID_HOME/ndk/25.2.9519653" />
                  <define name="JAVA_HOME" value="$JAVA_HOME" />
                  <define name="ANDROID_SETUP" value="true" />
              </section>
          </config>
          EOF
          cat ~/.lime/config.xml

      - name: Compile
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_ROOT: ${{ env.ANDROID_HOME }}/ndk/25.2.9519653
        run: haxelib run lime build android -DDEMO -Ddebug --verbose

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: androidBuild
          path: export/debug/android/bin/app/build/outputs/apk
